### ISSUE TITLE
segfault when clicking on a node in gui

### ISSUE THREAD

**Issue by tari3x** [paperManu/splash#25]
To reproduce: 
* splash splash.json
* in the gui, select "Camera" (there is also guiCamera)
* click in the camera view in the gui

inputs: http://ge.tt/5xIQrsi2

Let me know if I should collect any more info.

```
#0  0x00000000005988d5 in std::_Hashtable<std::string, std::pair<std::string const, Splash::AttributeFunctor>, std::allocator<std::pair<std::string const, Splash::AttributeFunctor> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find(std::string const&) ()
#1  0x0000000000596e89 in Splash::BaseObject::setAttribute(std::string const&, std::deque<Splash::Value, std::allocator<Splash::Value> > const&) ()
#2  0x00000000007487f1 in Splash::Camera::render() ()
#3  0x0000000000607862 in Splash::Scene::render() ()
#4  0x00000000006069ba in Splash::Scene::run() ()
#5  0x00007ffff0432e70 in  () at /usr/lib64/libstdc++.so.6
#6  0x00007ffff76810a4 in start_thread () at /lib64/libpthread.so.0
#7  0x00007fffefe9a02d in clone () at /lib64/libc.so.6
```

**Comment by paperManu** [comment]
I can't seem to reproduce this bug. Could you please recompile it with the debug flag and send my the backtrace ?

```
cd ${SPLASH_DIR}
mkdir -p build && cd build
rm -rf *
cmake -DCMAKE_BUILD_TYPE=Debug ..
make && sudo make install
```

**Comment by tari3x** [comment]
Sure. I wonder if the startup warnings have to do with this?

```
GNU gdb (GDB; openSUSE Leap 42.1) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/avatar/install/splash/build/src/splash...done.
(gdb) run
Starting program: /home/avatar/install/splash/build/src/splash splash.json
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.19-22.1.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffdf718700 (LWP 4983)]
[New Thread 0x7fffdef17700 (LWP 4984)]
[New Thread 0x7fffde716700 (LWP 4985)]
[New Thread 0x7fffddf15700 (LWP 4986)]
[New Thread 0x7fffdd714700 (LWP 4987)]
[New Thread 0x7fffdcd07700 (LWP 4988)]
[New Thread 0x7fffdc506700 (LWP 4989)]
[New Thread 0x7fffdbd05700 (LWP 4990)]
[New Thread 0x7fffdb504700 (LWP 4991)]
[New Thread 0x7fffdad03700 (LWP 4992)]

                     - Splash -
        - Modular multi-output video mapper -
                  - Version 0.5.6 -

2017-02-22T00:03:10 / [MESSAGE] / World::applyConfig - Starting an inner Scene
2017-02-22T00:03:10 / [MESSAGE] / Scene::init - GL version: 4.3
[New Thread 0x7fffd918f700 (LWP 4993)]
[New Thread 0x7fffd898e700 (LWP 4994)]
[New Thread 0x7fffcbfff700 (LWP 4995)]
[New Thread 0x7fffcb7fe700 (LWP 4996)]
[New Thread 0x7fffc3fff700 (LWP 4997)]
[New Thread 0x7fffcaffd700 (LWP 4998)]
[New Thread 0x7fffca7fc700 (LWP 4999)]
2017-02-22T00:03:11 / [MESSAGE] / Gui::Gui - Framebuffer object successfully initialized
2017-02-22T00:03:11 / [MESSAGE] / Camera::init - Framebuffer object successfully initialized
2017-02-22T00:03:11 / [MESSAGE] / Camera::init - Camera correctly initialized
2017-02-22T00:03:11 / [WARNING] / Camera::loadDefaultModels - File 2d_marker.obj does not seem to be readable.
2017-02-22T00:03:11 / [WARNING] / Camera::loadDefaultModels - File 3d_marker.obj does not seem to be readable.
2017-02-22T00:03:11 / [WARNING] / Camera::loadDefaultModels - File camera.obj does not seem to be readable.
[New Thread 0x7fffc9ffb700 (LWP 5000)]
[New Thread 0x7fffc97fa700 (LWP 5001)]
[New Thread 0x7fffc8ff9700 (LWP 5002)]
[New Thread 0x7fffc37fe700 (LWP 5003)]
2017-02-22T00:03:11 / [MESSAGE] / Camera::init - Framebuffer object successfully initialized
2017-02-22T00:03:11 / [MESSAGE] / Camera::init - Camera correctly initialized
2017-02-22T00:03:11 / [WARNING] / Camera::loadDefaultModels - File 2d_marker.obj does not seem to be readable.
2017-02-22T00:03:11 / [WARNING] / Camera::loadDefaultModels - File 3d_marker.obj does not seem to be readable.
2017-02-22T00:03:11 / [WARNING] / Camera::loadDefaultModels - File camera.obj does not seem to be readable.
2017-02-22T00:03:11 / [MESSAGE] / Window::Window - Window created successfully
2017-02-22T00:03:11 / [MESSAGE] / Window::Window - Render framebuffer object successfully initialized
2017-02-22T00:03:11 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
2017-02-22T00:03:11 / [MESSAGE] / Window::Window - Window created successfully
2017-02-22T00:03:11 / [MESSAGE] / Window::Window - Render framebuffer object successfully initialized
2017-02-22T00:03:11 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
2017-02-22T00:03:11 / [MESSAGE] / Warp::init - Framebuffer object successfully initialized
2017-02-22T00:03:11 / [MESSAGE] / Warp::init - Warp correctly initialized
2017-02-22T00:03:11 / [WARNING] / Warp::loadDefaultModels - File 3d_marker.obj does not seem to be readable.
2017-02-22T00:03:11 / [MESSAGE] / Filter::init - Framebuffer object successfully initialized
2017-02-22T00:03:11 / [MESSAGE] / Filter::init - Filter correctly initialized
2017-02-22T00:03:11 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
ALSA lib pcm_dsnoop.c:615:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1039:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1039:(snd_pcm_dmix_open) unable to open slave
2017-02-22T00:03:11 / [MESSAGE] / Window::setupReadFBO - Read framebuffer object successfully initialized
[New Thread 0x7fffc19e2700 (LWP 5011)]
[Thread 0x7fffc19e2700 (LWP 5011) exited]
[New Thread 0x7fffc19e2700 (LWP 5012)]
[New Thread 0x7fffd8158700 (LWP 5013)]
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
[Thread 0x7fffc19e2700 (LWP 5012) exited]
jack server is not running or cannot be started
2017-02-22T00:03:11 / [MESSAGE] / Sound_Engine::getDevice - Connected to device: default
[Thread 0x7fffd8158700 (LWP 5013) exited]
[New Thread 0x7fffc19e2700 (LWP 5014)]
[New Thread 0x7fffc11e1700 (LWP 5015)]
2017-02-22T00:03:11 / [MESSAGE] / Sound_Engine::startStream - Successfully opened PortAudio stream
2017-02-22T00:03:11 / [MESSAGE] / LtcClock::LtcClock - Input clock enabled
[New Thread 0x7fffc09e0700 (LWP 5016)]

Thread 17 "splash" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcaffd700 (LWP 4998)]
0x0000000000a271b8 in std::_Hashtable<std::string, std::pair<std::string const, Splash::AttributeFunctor>, std::allocator<std::pair<std::string const, Splash::AttributeFunctor> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_bucket_index (this=0x68, __k="position", __c=3102619767967782185) at /usr/include/c++/5/bits/hashtable.h:621
621           { return __hash_code_base::_M_bucket_index(__k, __c, _M_bucket_count); }
Missing separate debuginfos, use: zypper install Mesa-debuginfo-17.0.0-635.1.x86_64 Mesa-libGL1-debuginfo-17.0.0-635.1.x86_64 Mesa-libglapi0-debuginfo-11.0.8-154.2.x86_64 alsa-plugins-pulse-debuginfo-1.0.29-10.1.x86_64 fontconfig-debuginfo-2.11.0-5.1.x86_64 gsl-debuginfo-1.16-6.1.x86_64 libFLAC8-debuginfo-1.3.0-11.1.x86_64 libHalf12-debuginfo-2.2.0-37.2.x86_64 libICE6-debuginfo-1.0.9-3.1.x86_64 libIex-2_2-12-debuginfo-2.2.0-37.2.x86_64 libIlmImf-2_2-22-debuginfo-2.2.0-37.2.x86_64 libIlmThread-2_2-12-debuginfo-2.2.0-37.2.x86_64 libSM6-debuginfo-1.2.2-5.1.x86_64 libX11-6-debuginfo-1.6.3-9.1.x86_64 libX11-xcb1-debuginfo-1.6.3-9.1.x86_64 libXau6-debuginfo-1.0.8-6.1.x86_64 libXcursor1-debuginfo-1.1.14-6.1.x86_64 libXdamage1-debuginfo-1.1.4-9.1.x86_64 libXext6-debuginfo-1.3.3-3.1.x86_64 libXfixes3-debuginfo-5.0.1-7.1.x86_64 libXi6-debuginfo-1.7.5-6.1.x86_64 libXinerama1-debuginfo-1.1.3-5.1.x86_64 libXrandr2-debuginfo-1.5.0-3.1.x86_64 libXrender1-debuginfo-0.9.9-3.1.x86_64 libXv1-debuginfo-1.0.10-7.1.x86_64 libXxf86vm1-debuginfo-1.1.4-1.1.x86_64 libasound2-debuginfo-1.0.29-10.1.x86_64 libavcodec57-debuginfo-3.2.20170206.68ed682710-2.1.x86_64 libavformat57-debuginfo-3.2.4-126.2.x86_64 libavutil55-debuginfo-3.2.4-128.1.x86_64 libbluray1-debuginfo-0.8.1-3.2.x86_64 libbz2-1-debuginfo-1.0.6-32.1.x86_64 libcelt0-2-debuginfo-0.11.1-17.1.x86_64 libdbus-1-3-debuginfo-1.8.22-10.1.x86_64 libdc1394-22-debuginfo-2.2.3-2.2.x86_64 libdrm2-debuginfo-2.4.75-204.2.x86_64 libdrm_intel1-debuginfo-2.4.75-204.2.x86_64 libdrm_nouveau2-debuginfo-2.4.75-204.2.x86_64 libdrm_radeon1-debuginfo-2.4.75-204.2.x86_64 libexif12-debuginfo-0.6.21-10.1.x86_64 libexpat1-debuginfo-2.1.0-20.1.x86_64 libfdk-aac1-debuginfo-0.1.5.git.1477639580.5fd7e65-1.1.x86_64 libffi4-debuginfo-5.3.1+r233831-6.1.x86_64 libfreetype6-debuginfo-2.5.5-8.2.x86_64 libgcc_s1-debuginfo-5.3.1+r233831-6.1.x86_64 libgcrypt20-debuginfo-1.6.1-32.1.x86_64 libglib-2_0-0-debuginfo-2.44.1-2.3.x86_64 libgmodule-2_0-0-debuginfo-2.44.1-2.3.x86_64 libgmp10-debuginfo-5.1.3-4.4.x86_64 libgnutls28-debuginfo-3.2.15-8.1.x86_64 libgobject-2_0-0-debuginfo-2.44.1-2.3.x86_64 libgpg-error0-debuginfo-1.13-3.6.x86_64 libgphoto2-6-debuginfo-2.5.8-5.1.x86_64 libgsm1-debuginfo-1.0.13-26.1.x86_64 libgstapp-1_0-0-debuginfo-1.10.3-78.1.x86_64 libgstaudio-1_0-0-debuginfo-1.10.3-78.1.x86_64 libgstpbutils-1_0-0-debuginfo-1.10.3-78.1.x86_64 libgstreamer-1_0-0-debuginfo-1.10.3-82.1.x86_64 libgstriff-1_0-0-debuginfo-1.10.3-78.1.x86_64 libgsttag-1_0-0-debuginfo-1.10.3-78.1.x86_64 libgstvideo-1_0-0-debuginfo-1.10.3-78.1.x86_64 libhogweed2-debuginfo-2.7.1-9.1.x86_64 libjack0-debuginfo-1.9.9.5-5.1.x86_64 libjasper1-debuginfo-1.900.14-170.1.x86_64 libjbig2-debuginfo-2.0-3.2.x86_64 libjpeg8-debuginfo-8.0.2-31.3.x86_64 libjson-c2-debuginfo-0.12-4.2.x86_64 libltdl7-debuginfo-2.4.2-16.6.x86_64 liblzma5-debuginfo-5.0.5-3.5.x86_64 libmp3lame0-debuginfo-3.99.5-1015.2.x86_64 libnettle4-debuginfo-2.7.1-9.1.x86_64 libnuma1-debuginfo-2.0.9-8.1.x86_64 libogg0-debuginfo-1.3.0-3.2.x86_64 libopencv3_1-debuginfo-3.1.0-97.32.x86_64 libopenjpeg1-debuginfo-1.5.2-5.1.x86_64 libopenssl1_0_0-debuginfo-1.0.1i-21.1.x86_64 libopus0-debuginfo-1.1-5.1.x86_64 liborc-0_4-0-debuginfo-0.4.24-6.1.x86_64 libp11-kit0-debuginfo-0.20.3-10.1.x86_64 libpciaccess0-debuginfo-0.13.4-1.1.x86_64 libpcre1-debuginfo-8.39-5.1.x86_64 libpgm-5_2-0-debuginfo-5.2.122-3.6.x86_64 libpng16-16-debuginfo-1.6.8-7.1.x86_64 libportaudio2-debuginfo-19_20140130-294.8.x86_64 libpulse0-debuginfo-7.0-5.1.x86_64 libpython3_4m1_0-debuginfo-3.4.5-8.1.x86_64 libqt4-debuginfo-4.8.6-13.1.x86_64 libqt4-x11-debuginfo-4.8.6-13.1.x86_64 libraw1394-11-debuginfo-2.1.0-5.1.x86_64 libschroedinger-1_0-0-debuginfo-1.0.11-10.1.x86_64 libsnappy1-debuginfo-1.1.3-1.1.x86_64 libsndfile1-debuginfo-1.0.25-24.1.x86_64 libsodium13-debuginfo-1.0.3-3.3.x86_64 libspeex1-debuginfo-1.2~rc2-1.1.x86_64 libstdc++6-debuginfo-5.3.1+r233831-6.1.x86_64 libswresample2-debuginfo-3.2.20170206.68ed682710-2.1.x86_64 libswscale4-debuginfo-3.2.20170206.68ed682710-2.1.x86_64 libtasn1-6-debuginfo-3.7-12.1.x86_64 libtheoradec1-debuginfo-1.1.1-28.1.x86_64 libtheoraenc1-debuginfo-1.1.1-28.1.x86_64 libtiff5-debuginfo-4.0.7-15.1.x86_64 libtwolame0-debuginfo-0.3.13-2.3.x86_64 libudev1-debuginfo-210-101.1.x86_64 libusb-1_0-0-debuginfo-1.0.20-1.1.x86_64 libuuid1-debuginfo-2.25-18.1.x86_64 libv4l1-0-debuginfo-0.8.9-3.3.x86_64 libv4l2-0-debuginfo-0.8.9-3.3.x86_64 libv4lconvert0-debuginfo-0.8.9-3.3.x86_64 libva-drm1-debuginfo-1.6.0-3.2.x86_64 libva-x11-1-debuginfo-1.6.0-3.2.x86_64 libva1-debuginfo-1.6.0-3.2.x86_64 libvdpau1-debuginfo-1.1.1-8.6.x86_64 libvorbis0-debuginfo-1.3.3-3.7.x86_64 libvorbisenc2-debuginfo-1.3.3-3.7.x86_64 libvpx1-debuginfo-1.3.0-3.2.x86_64 libwebp5-debuginfo-0.4.3-7.1.x86_64 libx264-148-debuginfo-0.148svn20161219-5.1.x86_64 libx265-102-debuginfo-2.2-1.1.x86_64 libxcb-dri2-0-debuginfo-1.11.1-1.1.x86_64 libxcb-dri3-0-debuginfo-1.11.1-1.1.x86_64 libxcb-glx0-debuginfo-1.11.1-1.1.x86_64 libxcb-present0-debuginfo-1.11.1-1.1.x86_64 libxcb-render0-debuginfo-1.11.1-1.1.x86_64 libxcb-shape0-debuginfo-1.11.1-1.1.x86_64 libxcb-shm0-debuginfo-1.11.1-1.1.x86_64 libxcb-sync1-debuginfo-1.11.1-1.1.x86_64 libxcb-xfixes0-debuginfo-1.11.1-1.1.x86_64 libxcb1-debuginfo-1.11.1-1.1.x86_64 libxml2-2-debuginfo-2.9.1-22.1.x86_64 libxshmfence1-debuginfo-1.2-5.3.x86_64 libxvidcore4-debuginfo-1.3.4-3.1.x86_64 libz1-debuginfo-1.2.8-8.1.x86_64 libzmq5-debuginfo-4.1.2-3.1.x86_64 s2tc-debuginfo-1.0-9.2.x86_64 systemd-debuginfo-210-101.1.x86_64
(gdb) bt
#0  0x0000000000a271b8 in std::_Hashtable<std::string, std::pair<std::string const, Splash::AttributeFunctor>, std::allocator<std::pair<std::string const, Splash::AttributeFunctor> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_bucket_index(std::string const&, unsigned long) const (this=0x68, __k="position", __c=3102619767967782185)
    at /usr/include/c++/5/bits/hashtable.h:621
#1  0x0000000000a25bb2 in std::_Hashtable<std::string, std::pair<std::string const, Splash::AttributeFunctor>, std::allocator<std::pair<std::string const, Splash::AttributeFunctor> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find(std::string const&) (this=0x68, __k="position") at /usr/include/c++/5/bits/hashtable.h:1306
#2  0x0000000000a246b3 in std::unordered_map<std::string, Splash::AttributeFunctor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, Splash::AttributeFunctor> > >::find(std::string const&) (this=0x68, __x="position")
    at /usr/include/c++/5/bits/unordered_map.h:615
#3  0x0000000000a1d85a in Splash::BaseObject::setAttribute(std::string const&, std::deque<Splash::Value, std::allocator<Splash::Value> > const&) (this=0x0, attrib="position", args=std::deque with 3 elements = {...}) at /home/avatar/install/splash/src/basetypes.cpp:195
#4  0x0000000000ca414e in Splash::Camera::render() (this=0x7fffac000cb0) at /home/avatar/install/splash/src/camera.cpp:701
#5  0x0000000000acaefc in Splash::Scene::render() (this=0x27a0280) at /home/avatar/install/splash/src/scene.cpp:425
#6  0x0000000000acb445 in Splash::Scene::run() (this=0x27a0280) at /home/avatar/install/splash/src/scene.cpp:468
#7  0x00000000009d5519 in Splash::World::<lambda()>::operator()(void) const (__closure=0x2a5b4c8) at /home/avatar/install/splash/src/world.cpp:267
#8  0x00000000009f8b36 in std::_Bind_simple<Splash::World::applyConfig()::<lambda()>()>::_M_invoke<>(std::_Index_tuple<>) (this=0x2a5b4c8) at /usr/include/c++/5/functional:1531
#9  0x00000000009f8a91 in std::_Bind_simple<Splash::World::applyConfig()::<lambda()>()>::operator()(void) (this=0x2a5b4c8) at /usr/include/c++/5/functional:1520
#10 0x00000000009f89ee in std::thread::_Impl<std::_Bind_simple<Splash::World::applyConfig()::<lambda()>()> >::_M_run(void) (this=0x2a5b4b0) at /usr/include/c++/5/thread:115
#11 0x00007ffff042fe70 in  () at /usr/lib64/libstdc++.so.6
#12 0x00007ffff76810a4 in start_thread () at /lib64/libpthread.so.0
#13 0x00007fffefe9702d in clone () at /lib64/libc.so.6

```

**Comment by paperManu** [comment]
This is clearly linked to the warnings.
It looks like you are starting the program from the build directory, you should install it:
```
cd /home/avatar/install/splash/build/
make && sudo make install
```
This will copy the needed obj files to the correct directory, and it should then work. Splash tries to load the .obj files from ${PREFIX}/share/splash, with ${PREFIX}=/usr/local in your case, and as you did not install it these obj files do not exist.

I'll change these warnings to errors, so that Splash does not launch if it can't find these files.

**Comment by tari3x** [comment]
Installing helped!
