### ISSUE TITLE
Assertion error: pcm.c:2757

### ISSUE THREAD

**Issue by charlesveasey** [paperManu/splash#46]
OS:  lubuntu 16.04 Alternate 64-bit

splash: pcm.c:2757: snd_pcm_area_copy: Assertion `src < dst || src >= dst + bytes' failed.
Aborted (core dumped)

**Comment by paperManu** [comment]
Hi Charles,

Do you have more precisions about your issue? Like a step-by-step procedure to reproduce it?

**Comment by charlesveasey** [comment]
Hello,

It's the default behaviour on my system with a new install of Lubuntu and Splash. The error is consistent, but sporadic in terms of timing. Raising the "World Framerate" to 999 helps to reduce the issue. Typing splash into terminal:

	             - Splash -
	- Modular multi-output video mapper -
	          - Version 0.7.13 -

```
2018-02-02T08:25:29 / [MESSAGE] / No filename specified, loading default file
2018-02-02T08:25:29 / [MESSAGE] / World::applyConfig - Starting an inner Scene
2018-02-02T08:25:30 / [MESSAGE] / Scene::init - GL version: 4.5
2018-02-02T08:25:30 / [MESSAGE] / Window::Window - Window created successfully
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
2018-02-02T08:25:30 / [MESSAGE] / Sound_Engine::getDevice - Connected to device: default
2018-02-02T08:25:30 / [MESSAGE] / Sound_Engine::startStream - Successfully opened PortAudio stream
2018-02-02T08:25:30 / [MESSAGE] / LtcClock::LtcClock - Input clock enabled
splash: pcm.c:2757: snd_pcm_area_copy: Assertion `src < dst || src >= dst + bytes' failed.
```

**Comment by paperManu** [comment]
Could you please:
- compile Splash in debug mode:
```
cmake -DCMAKE_BUILD_TYPE=Debug ..
make -j$(nproc) && sudo make install
```
- run Splash, wait for the crash to happen
- send me the core dump

Thanks!

**Comment by charlesveasey** [comment]
Where is the core dump file? 

I captured this using gdb, if that helps:
```
#0  0x00007ffff4c5d428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff4c5f02a in __GI_abort () at abort.c:89
#2  0x00007ffff4c55bd7 in __assert_fail_base (fmt=<optimized out>, 
    assertion=assertion@entry=0x7ffff3d58018 "src < dst || src >= dst + bytes", file=file@entry=0x7ffff3d5cbe5 "pcm.c", 
    line=line@entry=2757, function=function@entry=0x7ffff3d5a290 "snd_pcm_area_copy") at assert.c:92
#3  0x00007ffff4c55c82 in __GI___assert_fail (assertion=0x7ffff3d58018 "src < dst || src >= dst + bytes", 
    file=0x7ffff3d5cbe5 "pcm.c", line=2757, function=0x7ffff3d5a290 "snd_pcm_area_copy") at assert.c:101
#4  0x00007ffff3ce51a8 in snd_pcm_area_copy () from /usr/lib/x86_64-linux-gnu/libasound.so.2
#5  0x00007ffff3ce539c in snd_pcm_areas_copy () from /usr/lib/x86_64-linux-gnu/libasound.so.2
#6  0x00007ffff3d265a5 in ?? () from /usr/lib/x86_64-linux-gnu/libasound.so.2
#7  0x00007ffff3cf719f in ?? () from /usr/lib/x86_64-linux-gnu/libasound.so.2
#8  0x00007ffff3cf6fd9 in ?? () from /usr/lib/x86_64-linux-gnu/libasound.so.2
#9  0x00007ffff3cf7681 in ?? () from /usr/lib/x86_64-linux-gnu/libasound.so.2
#10 0x00007ffff5e20be7 in ?? () from /usr/lib/x86_64-linux-gnu/libportaudio.so.2
#11 0x00007ffff5e28870 in ?? () from /usr/lib/x86_64-linux-gnu/libportaudio.so.2
#12 0x00007ffff767f6ba in start_thread (arg=0x7fffd4ddf700) at pthread_create.c:333
#13 0x00007ffff4d2f41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

```

**Comment by paperManu** [comment]
By any chance, do you have an audio input on your computer? It looks like it crashes when trying to read the LTC clock, although everything seems to have been initialized correctly.

**Comment by charlesveasey** [comment]
There's an audio input on this motherboard, but there isn't anything plugged into it.

**Comment by paperManu** [comment]
The input not being plugged to anything should not be an issue.
The core dump should be in the directory you ran Splash from, and named core.*. If not, you could check in /tmp/core.*

**Comment by paperManu** [comment]
This issue is related to a bug in Alsa / Pulseaudio : http://mailman.alsa-project.org/pipermail/alsa-devel/2016-June/108915.html

It has been solved since, the best fix is to update the system.
